config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root to: 'home_pages#index'

    get   :cart,     to: "orders#edit",     as: :cart
    patch :cart,     to: "orders#update",   as: :update_cart
    post  :populate, to: "orders#populate", as: :populate

    patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
    get   '/checkout/:state',        to: 'checkout#edit',   as: :checkout_state
    get   '/checkout',               to: 'checkout#edit',   as: :checkout

    resources :products, only: :show do
      get :search, on: :collection
    end

    resources :categories,          only: :show
    resources :orders,              only: [:show, :edit, :update]
    resources :line_items,          only: :destroy
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/potepan/line_item_decorator.rb
module Potepan::LineItemDecorator
  def image_pickup
    variant.gallery.images.first || product.image_pickup
  end

  Spree::LineItem.prepend self
end

app/models/potepan/option_type_decorator.rb
module Potepan::OptionTypeDecorator
  def self.prepended(base)
    base.scope :colors, -> { find_by(presentation: "Color").option_values }
    base.scope :sizes,  -> { find_by(presentation: "Size").option_values }
  end

  Spree::OptionType.prepend self
end

app/models/potepan/order_decorator.rb
module Potepan::OrderDecorator
  def previous_state
    case state
    when "address"
      "cart"
    when "payment"
      "address"
    when "confirm"
      "payment"
    end
  end

  def payment_status_design
    case state
    when "address"
      "disabled"
    when "payment"
      "active"
    when "confirm"
      "complete fullBar"
    end
  end

  def pay_by_credit_card
    available_payment_methods.find_by(name: "Credit Card")
  end

  def insufficient_stock_line_items
    line_items.includes(:variant).select(&:insufficient_stock?)
  end

  Spree::Order.prepend self
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  def related_products
    Spree::Product.in_taxons(taxons).distinct.
      where.not(id: id).
      includes(master: [:default_price, :images])
  end

  def image_pickup
    images.first || Spree::Image.new
  end

  def self.prepended(base)
    base.scope :desc_by_available, -> do
      base.includes(master: [:default_price, :images]).
        order(available_on: :desc).
        where("available_on <= ?", Time.current)
    end

    base.scope :with_sort_by, -> (sort) do
      return if sort.blank?
      case sort
      when "NEW_PRODUCT"
        base.order(available_on: :desc)
      when "OLD_PRODUCT"
        base.order(available_on: :asc)
      when "HIGH_PRICE"
        base.descend_by_master_price
      when "LOW_PRICE"
        base.ascend_by_master_price
      end
    end

    base.scope :filter_by_value, -> (value) do
      return if value.blank?
      base.joins(variants: :option_values).
        where(spree_option_values: { presentation: value })
    end

    base.scope :search_by, -> (word) do
      base.includes(master: [:default_price, :images]).
        where("name LIKE :word OR description LIKE :word", word: "%#{sanitize_sql_like(word)}%")
    end

    def base.with_filter_and_sort(filter:, sort:)
      filter_by_value(filter).with_sort_by(sort).uniq
    end
  end

  Spree::Product.prepend self
end

app/models/potepan/taxon_decorator.rb
module Potepan::TaxonDecorator
  POPULAR_TAXONS = %w(bags categories t-shirts).freeze

  def self.prepended(base)
    def base.three_popular_taxons
      where(name: POPULAR_TAXONS).order(:name)
    end
  end

  Spree::Taxon.prepend self
end

app/models/potepan/wallet_decorator.rb
module Potepan::WalletDecorator
  def payment_source_of_wallet
    user.wallet_payment_sources.includes(:payment_source)
  end

  Spree::Wallet.prepend self
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @category = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(taxons: :products)
    @option_colors = Spree::OptionType.colors
    @option_sizes = Spree::OptionType.sizes

    @products = @category.
      all_products.includes(master: [:default_price, :images]).
      with_filter_and_sort(filter: params[:value], sort: params[:sort])
  end
end

app/controllers/potepan/checkout_controller.rb
class Potepan::CheckoutController < ApplicationController
  before_action :load_order
  before_action :set_state_if_present

  before_action :ensure_order_not_completed
  before_action :ensure_checkout_allowed
  before_action :ensure_sufficient_stock_lines
  before_action :ensure_valid_state

  before_action :associate_user
  before_action :check_authorization

  before_action :setup_for_current_state, only: [:edit, :update]

  rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error
  rescue_from Spree::Order::InsufficientStock, with: :insufficient_stock_error

  def update
    if update_order
      unless transition_forward
        redirect_on_failure
        return
      end
      if @order.completed?
        finalize_order
      else
        send_to_next_state
      end
    else
      render :edit
    end
  end

  private

  def update_order
    Spree::OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  end

  def redirect_on_failure
    flash[:error] = @order.errors.full_messages.join("\n")
    redirect_to(potepan_checkout_state_path(@order.state))
  end

  def transition_forward
    if @order.can_complete?
      @order.complete
    else
      @order.next
    end
  end

  def finalize_order
    @current_order = nil
    set_successful_flash_notice
    redirect_to completion_route
  end

  def set_successful_flash_notice
    flash.notice = t('spree.order_processed_successfully')
  end

  def send_to_next_state
    @order.next if @order.state == "delivery"
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def update_params
    update_params = massaged_params[:order]
    if update_params.present?
      update_params.permit(permitted_checkout_attributes)
    else
      # currently allow update requests without any parameters in them
      {}
    end
  end

  def massaged_params
    massaged_params = params.deep_dup

    move_payment_source_into_payments_attributes(massaged_params)
    if massaged_params[:order] && massaged_params[:order][:existing_card].present?
      move_existing_card_into_payments_attributes(massaged_params)
    end
    move_wallet_payment_source_id_into_payments_attributes(massaged_params)
    set_payment_parameters_amount(massaged_params, @order)

    massaged_params
  end

  # should be overriden if you add new checkout_step that don't match solidus checkout_steps
  def skip_state_validation?
    false
  end

  def load_order
    @order = current_order
    redirect_to(potepan_cart_path) && return unless @order
  end

  # go to next step if params[:state]
  def set_state_if_present
    if params[:state]
      if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
        redirect_to potepan_checkout_state_path(@order.state)
      end
      @order.state = params[:state]
    end
  end

  # check the order contains line_items
  def ensure_checkout_allowed
    unless @order.checkout_allowed?
      redirect_to potepan_cart_path
    end
  end

  # check the order is not completed yet
  def ensure_order_not_completed
    redirect_to potepan_cart_path if @order.completed?
  end

  # check the order's line_items have enough stock
  def ensure_sufficient_stock_lines
    if @order.insufficient_stock_line_items.present?
      out_of_stock_items = @order.insufficient_stock_line_items.collect(&:name).to_sentence
      flash[:error] =
        t('spree.inventory_error_flash_for_insufficient_quantity', names: out_of_stock_items)
      redirect_to potepan_cart_path
    end
  end

  # check if the order can go to checkout step
  def ensure_valid_state
    unless skip_state_validation?
      if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
        (!params[:state] && !@order.has_checkout_step?(@order.state))
        @order.state = 'cart'
        redirect_to potepan_cart_path
      end
    end
  end

  def completion_route
    potepan_order_path(@order.number)
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  # set the default country for filing address (default: Japan)
  def before_address
    @order.assign_default_user_addresses
    default = { country: Spree::Country.find_by(name: "Japan") }
    @order.build_ship_address(default) unless @order.ship_address
  end

  def before_delivery
    return if params[:order].present?

    packages = @order.shipments.map(&:to_package)
    @differentiator = Spree::Stock::Differentiator.new(@order, packages)
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      @differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end

    if try_spree_current_user && try_spree_current_user.respond_to?(:wallet)
      @wallet_payment_sources = try_spree_current_user.wallet.wallet_payment_sources
      @default_wallet_payment_source = @wallet_payment_sources.detect(&:default) ||
                                      @wallet_payment_sources.first

      @payment_sources = try_spree_current_user.
        wallet.payment_source_of_wallet.
        map(&:payment_source).
        select { |ps| ps.is_a?(Spree::CreditCard) }
    end
  end

  def rescue_from_spree_gateway_error(exception)
    flash.now[:error] = t('spree.spree_gateway_error_flash_for_checkout')
    @order.errors.add(:base, exception.message)
    render :edit
  end

  def check_authorization
    authorize!(:edit, current_order, cookies.signed[:guest_token])
  end

  def insufficient_stock_error
    packages = @order.shipments.map(&:to_package)
    if packages.empty?
      flash[:error] = I18n.t('spree.insufficient_stock_for_order')
      redirect_to cart_path
    else
      availability_validator = Spree::Stock::AvailabilityValidator.new
      unavailable_items = @order.line_items.
        reject { |line_item| availability_validator.validate(line_item) }
      if unavailable_items.any?
        item_names = unavailable_items.map(&:name).to_sentence
        flash[:error] =
          t('spree.inventory_error_flash_for_insufficient_shipment_quantity',
            unavailable_items: item_names)
        @order.restart_checkout_flow
        redirect_to spree.checkout_state_path(@order.state)
      end
    end
  end

  def deprecated_payment_sources
    try_spree_current_user.wallet.payment_source_of_wallet.
      map(&:payment_source).
      select { |ps| ps.is_a?(Spree::CreditCard) }
  end
end

app/controllers/potepan/home_pages_controller.rb
class Potepan::HomePagesController < ApplicationController
  NEW_PRODUCTS_LIMIT = 8

  def index
    @new_products = Spree::Product.desc_by_available.limit(NEW_PRODUCTS_LIMIT)
    @categories = Spree::Taxon.three_popular_taxons
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  def destroy
    line_item = Spree::LineItem.find_by(id: params[:id])
    line_item.destroy if line_item.present?
    redirect_back(fallback_location: potepan_root_path)
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  before_action :assign_order, only: :update
  rescue_from ActiveModel::RangeError, with: :rescue_from_so_many_quantity

  def show
    @order = Spree::Order.find_by!(number: params[:id])
    authorize! :read, @order, cookies.signed[:guest_token]
  end

  def edit
    @order = current_order || Spree::Order.incomplete.
      find_or_initialize_by(guest_token: cookies.signed[:guest_token])
    @line_items = @order.line_items.includes(variant: [:images, :product])
    authorize! :read, @order, cookies.signed[:guest_token]
    associate_user
  end

  def populate
    @order = current_order(create_order_if_necessary: true)
    authorize! :update, @order, cookies.signed[:guest_token]

    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1

    if !quantity.between?(1, 100)
      @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => error
      @order.errors.add(:base, error.record.errors.full_messages.join(", "))
    end

    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_back_or_default(potepan_root_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def update
    authorize! :update, @order, cookies.signed[:guest_token]
    if @order.contents.update_cart(order_params)
      if params.key?(:checkout)
        @order.next if @order.cart?
        redirect_to potepan_checkout_state_path(@order.state)
        return
      end
    end
    redirect_to potepan_cart_path
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end

  def assign_order
    @order = current_order
    unless @order
      flash[:error] = "Order not found."
      redirect_to potepan_root_path
      return
    end
  end

  def rescue_from_so_many_quantity
    flash[:error] = "Quantity is so big. The quantity should be less than 100 per product."
    redirect_back(fallback_location: potepan_cart_path)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  NUMBERS_OF_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products.sample(NUMBERS_OF_RELATED_PRODUCTS)
  end

  def search
    @search_word = params[:search]
    @products = Spree::Product.search_by(@search_word)
  end
end

app/helpers/potepan/home_pages_helper.rb
module Potepan::HomePagesHelper
  def go_to_products_page
    if Spree::Taxon.first.present?
      potepan_category_path(Spree::Taxon.first.id)
    else
      "#"
    end
  end
end

app/helpers/potepan/products_helper.rb
module Potepan::ProductsHelper
  def products_count_for_option(value:, category:)
    Spree::Product.includes(variants: :option_values).
      in_taxon(category).
      where(spree_option_values: { presentation: value.presentation }).count
  end
end

app/views/potepan/products/_cart_form.html.erb
<% variants = product.variants %>
<%= form_with url: potepan_populate_path, local: true do |f| %>
  <% if variants.present? %>
    <span class="quick-drop">
      <%= f.select(:variant_id,
        options_from_collection_for_select(
          variants, :id, :options_text, variants.first.id
        ),{ },{ class: "select-drop" }
      )%>
    </span>
  <% else %>
    <%= f.hidden_field :variant_id, value: product.master.id %>
  <% end %>
  <span class="quick-drop resizeWidth">
    <%= f.select :quantity, (1..5).map {|n| [n, n]}, { selected: 1 }, { class:"select-drop" } %>
  </span>
  <div class="btn-area">
    <%= f.button class: 'btn btn-primary btn-block', type: :submit do %>
      カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/potepan/products/_product.html.erb
<div class= <%= layout %>>
  <div class="productBox">
    <%= link_to potepan_product_path(product.id), id: "product_#{product.id}_link" do %>
      <div class="productImage clearfix">
        <%= image_tag(product.image_pickup.url(:product), :alt => "#{product.name}-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/products/_single_product.html.erb
<div class="row singleProduct">
  <div class="col-xs-12">
    <div class="media">
      <div class="media-left productSlider">
        <div id="carousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% product.images.each_with_index do |image,i| %>
              <div class="item <%= 'active' if i.zero? %>" data-thumb= <%= i %> >
                <%= image_tag(image.url(:large)) %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="clearfix">
          <div id="thumbcarousel" class="carousel slide" data-interval="false">
            <div class="carousel-inner">
              <% product.images.each_with_index do |image, i| %>
                <div data-target="#carousel" data-slide-to=<%= i %> class="thumb">
                  <%= image_tag(image.url(:small)) %>
                </div>
              <% end %>
            </div>
            <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="media-body">
        <ul class="list-inline">
          <li id="back-to-category">
            <%= link_to potepan_category_path(product.taxons.first.id) do %>
              <i class="fa fa-reply" aria-hidden="true"></i>
              一覧ページへ戻る
            <% end %>
          </li>
        </ul>
        <h2><%= product.name %></h2>
        <h3><%= product.display_price %></h3>
        <p><%= product.description %></p>
        <%= render "cart_form", product: product %>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/search.html.erb
<% provide(:title, @search_word) %>
<%= render "shared/light_section", article_title: @search_word %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render partial: "potepan/products/product", collection: @products, locals: { layout: "col-sm-3 col-xs-12" } %>
    </div>
  </div>
</section>
<%= render "layouts/partners_logo_slider" %>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<%= render "shared/light_section", article_title: @product.name %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <%= render "single_product", product: @product %>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <%= render partial: "product", collection: @related_products, locals: { layout: "col-md-3 col-sm-6 col-xs-12" } %>
    </div>
  </div>
</section>